using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.MountAndBlade;
using TaleWorlds.MountAndBlade.GauntletUI.Widgets;
using TaleWorlds.Library;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM), nameof(SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM.SetAttributes))]
    internal class CinematicsFullScreen
    {
		[HarmonyPostfix]
		static void Postfix(ref SceneNotification__TaleWorlds_Core_ViewModelCollection_Information_SceneNotificationVM __instance, ref Widget ____widget_0, ref SceneWidget ____widget_0_2_0)
		{
            Vec2 res = MBWindowManager.GetScreenResolution();
            ____widget_0_2_0.SuggestedHeight = res.Y + 40f;
            ____widget_0_2_0.SuggestedWidth = res.X + 40f;
        }
    }
}
