using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using SandBox.GauntletUI.AutoGenerated1;
using TaleWorlds.GauntletUI.BaseTypes;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM), nameof(EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM.SetAttributes))]
    internal class EncyclopediaStretch
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaHome__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaHomeVM __instance, ref Widget ____widget_0)
		{
			____widget_0.SuggestedHeight = 1440;
			____widget_0.SuggestedWidth = 2560;
        }
    }
}
