using HarmonyLib;
using SandBox.GauntletUI.AutoGenerated0;
using TaleWorlds.GauntletUI.BaseTypes;

namespace wipo.patches.UIstuff
{
    [HarmonyPatch(typeof(EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM), nameof(EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM.SetAttributes))]
    internal class EncyclopediaFullScreen
    {
		[HarmonyPostfix]
		static void Postfix(ref EncyclopediaBar__TaleWorlds_CampaignSystem_ViewModelCollection_Encyclopedia_EncyclopediaNavigatorVM __instance, ref Widget ____widget_1)
		{
			____widget_1.SuggestedHeight = 1480;
			____widget_1.SuggestedWidth = 2600;
        }
    }
}
